third task most part
Nearmeow/tasks_ibs pull request #3
Opened 2022-12-24 21:21 UTC by Nearmeow

Некорректно считывает дату с двухсимвольным годом.

2022-12-25 22:31 UTC, SidorovIgorAlex requested changes

2022-12-25 22:31 UTC, SidorovIgorAlex commented on src/main/java/task_3/InfoPrinter.java
> +            System.out.printf("ID владельца - %d, код - %s\n", sec.getOwner().getId(), sec.getCode());
Смотри, у тебя печатаются все акции для каждой компании, а надо печатать только по конкретным валютам, поправь здесь
Скорее всего, лучше в данный метод кроме листа акций, передавать и выбранную валюту
И более кратко будет через стримы это все сделать

2022-12-25 22:31 UTC, SidorovIgorAlex commented on src/main/java/task_3/InfoPrinter.java
> +        for (Security sec : oldSecurities) {
Тут тоже можно стримами сделать

2022-12-25 22:31 UTC, SidorovIgorAlex commented on src/main/java/task_3/InfoPrinter.java
> +            System.out.printf("%s - Дата основания %s\n", com.getName(), com.getFounded().format(CustomDateFormatter.PRINT_FORMATTER));
И тут)

2022-12-25 22:31 UTC, SidorovIgorAlex commented on src/main/java/task_3/CompanyHandler.java
> +        for (Company com : companies) {
В целом, попробуй чисто для практики переписать все это в виде стримов - это сделать код чуть менее громоздким

2022-12-26 11:45 UTC, Nearmeow commented on src/main/java/task_3/InfoPrinter.java
> +            System.out.printf("ID владельца - %d, код - %s\n", sec.getOwner().getId(), sec.getCode());
Этот метод получает уже отобранный по валюте список и только печатает его, обрабатывается список в классе CompanyHandler и там был как раз стрим) Ошибка была в том, что я перепутала EU и USD в текстовом сообщении, поправила это.

2022-12-28 15:58 UTC, merged